image: thyrlian/android-sdk:2.6

variables:
  KEYSTORE: $CI_PROJECT_DIR/signing.keystore
  CI_ARTIFACTS: /tmp/log
  ANDROID_COMPILE_SDK: '28'
  ANDROID_BUILD_TOOLS: '28.0.2'

stages:
  - build

android:
  stage: build
  allow_failure: true
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y curl python3
    - bash ./deployment/download_keystore.sh
    - python ./deployment/set_credentials.py
    - python ./deployment/set_version_code.py
    - python ./deployment/set_stats_url.py
    - mkdir /tmp/log && chmod 777 /tmp/log
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" > /dev/null
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  script:
    - cd hipayfullservice-android && ./gradlew build
    - cd .. && python ./deployment/create_hockeyapp_branch.py
    - python ./deployment/get_identifier.py > $CI_ARTIFACTS/app_identifier
    - bash ./deployment/deploy.sh
  artifacts:
    when: on_failure
    paths:
      - ./hipayfullservice-android/example/build/reports/
  tags:
    - pi-commerce-no-overlay
