image: $REGISTRY_CI/gitlab-ci-base-android

variables:
  ANDROID_COMPILE_SDK: '31'
  ANDROID_BUILD_TOOLS: '30.0.3'

stages:
  - test
  - build-demo
  - deploy-demo
  # - build-framework
  # - deploy-framework

test:
  stage: test
  allow_failure: false
  before_script:
    - ruby -v
    - gem -v
    - bundler -v
    - bundle install
  script:
    - bundle exec fastlane Test
  tags:
    - gcp-default-runner-prod

build-demo:
  stage: build-demo
  before_script:
    - bundle check || bundle install --path vendor/bundle
  script:
    - bundle exec fastlane BuildDemo
  artifacts:
    name: example-release.apk
    paths:
      - example/build/outputs/apk/release/example-release.apk
    expire_in: 60 mins
  tags:
    - gcp-default-runner-prod

deploy-demo:
  stage: deploy-demo
  before_script:
    - bundle check || bundle install --path vendor/bundle
  script:
    - bundle exec fastlane DeployDemo
  tags:
    - gcp-default-runner-prod

# build-framework:
#   stage: build-framework
#   allow_failure: false
#   before_script:
#     - bundle check || bundle install --path vendor/bundle
#   script:
#     - bundle exec fastlane BuildFramework
#   artifacts:
#     name: hipayfullservice-release.aar
#     paths:
#       - hipayfullservice/build/outputs/aar/hipayfullservice-release.aar
#     expire_in: 60 mins
#   tags:
#     - gcp-default-runner-prod
#   when: manual

# deploy-framework:
#   stage: deploy-framework
#   allow_failure: false
#   before_script:
#     - bundle check || bundle install --path vendor/bundle
#   script:
#     - bundle exec fastlane DeployFramework
#   tags:
#     - gcp-default-runner-prod