image: thyrlian/android-sdk:2.2

variables:
  KEYSTORE: $CI_PROJECT_DIR/signing.keystore
  CI_ARTIFACTS: /tmp/log

stages:
 - build
# - analysis
# - deploy
 - sync

android:
  stage: build
  before_script:
    - apt-get install -y curl python3
    - bash ./deployment/download_keystore.sh
    - python ./deployment/set_credentials.py
    - python ./deployment/set_version_code.py
    - mkdir /tmp/log && chmod 777 /tmp/log
  script:
    - cd hipayfullservice-android && ./gradlew build
    - cd .. && python ./deployment/create_hockeyapp_branch.py
    - python ./deployment/get_identifier.py > $CI_ARTIFACTS/app_identifier
    - bash ./deployment/deploy.sh
  allow_failure: false
#  artifacts:
#    paths:
#    - ./hipayfullservice-android/example/build/intermediates/
  tags:
    - sdk-android

#sonarqube:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: http://172.17.0.1:19000
#    SONAR_ANALYSIS_MODE: preview
#    SONAR_TOKEN: $SONAR_LOGIN
##  artifacts:
##    paths:
##    - ./hipayfullservice-android/example/build/intermediates/
#  script:
#  - cd hipayfullservice-android && ./gradlew build
#  - /usr/bin/sonar-scanner-run.sh -X
#
#sonarqube-reports:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: http://172.17.0.1:19000
#    SONAR_ANALYSIS_MODE: "publish"
#    SONAR_TOKEN: $SONAR_LOGIN
##  artifacts:
##    paths:
##    - ./hipayfullservice-android/example/build/intermediates/
#  script:
#  - cd hipayfullservice-android && ./gradlew build
#  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh

# Wait problem with GitlabCI Artifact
#deploy:
# stage: deploy
# script:
#  - apt-get install -y curl
#  - mkdir /tmp/log && chmod 777 /tmp/log
#  - bash ./deployment/deploy.sh
# artifacts:
#   paths:
#   - ./hipayfullservice-android/example/build/outputs/apk/example-release.apk

sync:
  stage: sync
  script:
  - git clone --mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.hipay.org/pi-ecommerce/hipay-fullservice-sdk-android.git
  - cd hipay-fullservice-sdk-android.git
  - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/hipay/hipay-fullservice-sdk-android.git
  allow_failure: true